# Use an official Python runtime as a parent image
FROM python:3.12.2

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY ./requirements.txt /app/

# Install Python dependencies
RUN pip install -r requirements.txt

# Copy the Flask application into the container
COPY . /app/

# Expose port 5000 for Flask
EXPOSE 5000

# Define the command to run the Flask application
CMD ["python", "app.py"]