"""Add subscription_level column to User model

Revision ID: 25fb26e51b3b
Revises: b9e694a69f8e
Create Date: 2024-04-05 10:35:58.302013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25fb26e51b3b'
down_revision = 'b9e694a69f8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_level', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('subscription_level')

    # ### end Alembic commands ###
